
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

server:
  port: 9001
  tomcat:
    connection-timeout: 60s
    keep-alive-timeout: 60s
    threads:
      max: 50
      min-spare: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!
  arctic:
    hello: Welcome to the north pole!

